POST http://localhost:8080/users/bulk
Content-Type: application/json

[
  {
    "id": 1,
    "name": "vishal",
    "age": 15
  },
  {
    "id": 2,
    "name": "rahul",
    "age": 20
  },
  {
    "id": 3,
    "name": "aman",
    "age": 52
  }
]
### Get all users
GET http://localhost:8080/users

### Delete user by ID
DELETE http://localhost:8080/users/1

### Get all users
GET http://localhost:8080/users

### Put a user
PUT http://localhost:8080/users/1
Content-Type: application/json

{
  "id": 1,
  "name": "vishal updated",
  "age": 25
}

### Using patch
